object AppDependencies {
    const val constraint_layout = "androidx.constraintlayout:constraintlayout:${Versions.constraint_layout}"
    const val kotlin_version = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.kotlin_version}"
    const val kotlin_core_ktx = "androidx.core:core-ktx:${Versions.ktx}"
    const val appcompat = "androidx.appcompat:appcompat:${Versions.appcompat}"
    const val material_guideline = "com.google.android.material:material:${Versions.material}"
    const val junit = "junit:junit:${Versions.junit}"
    const val junit_extension = "androidx.test.ext:junit:${Versions.junit_ext}"
    const val espresso = "androidx.test.espresso:espresso-core:${Versions.espresso}"
    const val room_runtime = "androidx.room:room-runtime:${Versions.room_version}"
    const val room_compiler = "androidx.room:room-compiler:${Versions.room_version}"
    const val room_ktx = "androidx.room:room-ktx:${Versions.room_version}"
    const val legacy_support = "androidx.legacy:legacy-support-v4:${Versions.legacy_support}"
    const val navigation_fragment_ktx = "androidx.navigation:navigation-fragment-ktx:${Versions.navigation_fragment_ktx}"
    const val navigation_ui_ktx = "androidx.navigation:navigation-ui-ktx:${Versions.navigation_ui_ktx}"
    const val fragment_ktx = "androidx.fragment:fragment-ktx:${Versions.fragment_ktx}"
    const val coroutine = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutine_android}"
    const val dagger_hilt = "com.google.dagger:hilt-android:${Versions.dagger_hilt}"
    const val dagger_hilt_android_compiler = "com.google.dagger:hilt-android-compiler:${Versions.dagger_hilt_android_compiler}"
    const val dagger_hilt_viewmodel = "androidx.hilt:hilt-lifecycle-viewmodel:${Versions.dagger_hilt_viewmodel}"
    const val dagger_hilt_compiler = "androidx.hilt:hilt-compiler:${Versions.dagger_hilt_compiler}"
    const val viewpager2 = "androidx.viewpager2:viewpager2:${Versions.viewpager2}"
    const val viewpager_indicator = "com.tbuonomo.andrui:viewpagerdotsindicator:${Versions.viewpager_indicator}"
    const val awesome_dialog = "com.github.chnouman:AwesomeDialog:${Versions.awesome_dialog}"
    const val permission_x = "com.permissionx.guolindev:permissionx:${Versions.permission_x}"
}